import {DEFAULT_CHARGE, defaultState, validate, solve, importState} from './model.mjs';
const $ = id => document.getElementById(id), svg = $('diagram'), NS = 'http://www.w3.org/2000/svg';
const COLORS = ['#435b76', '#a55c35', '#8058a0', '#8b7521'], DISPLAY = ['vectors','sum','construction','guides','grid'];
let state = defaultState(), history = [], units = {}, tool = 'move', drag = null, transform, result, effectiveScale, inputInvalid = false;
const clone = s => structuredClone(s);
function fmt(v) {if (Math.abs(v)<1e-12) return '0'; return (Math.abs(v)<.01||Math.abs(v)>=1e6)?v.toExponential(2).replace('.',','):v.toLocaleString('de-DE',{maximumFractionDigits:2});}
function num(input,name){const raw=input.value.trim().replace(',','.');if(!/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?$/i.test(raw)||!Number.isFinite(Number(raw)))throw Error(`${name}: Bitte eine gültige Zahl eingeben (auch Komma und z. B. 1e-11 möglich).`);return Number(raw);}
function sync(){
 $('sources').replaceChildren();
 for(const q of state.sources){const card=document.createElement('div');card.className='source-card';card.dataset.source=q.id;
  card.innerHTML=`<div class="source-head"><strong style="color:${COLORS[q.id-1]}">Q${q.id}</strong><button type="button" data-remove="${q.id}" aria-label="Q${q.id} entfernen">Entfernen</button></div><div class="row"><label for="x${q.id}">x / cm<input id="x${q.id}" data-key="x" inputmode="decimal"></label><label for="y${q.id}">y / cm<input id="y${q.id}" data-key="y" inputmode="decimal"></label></div><div class="row"><label for="s${q.id}">Vorzeichen<select id="s${q.id}" data-key="sign"><option value="1">+ positiv</option><option value="-1">− negativ</option></select></label><div><label for="q${q.id}">Ladungsbetrag |Q${q.id}|</label><div class="charge-entry"><input id="q${q.id}" data-key="charge" inputmode="decimal"><select id="unit${q.id}" aria-label="Ladungseinheit Q${q.id}" data-key="unit"><option value="pC">pC</option><option value="nC">nC</option></select></div></div></div>`;
  $('sources').append(card);units[q.id]??='pC';$('x'+q.id).value=q.x;$('y'+q.id).value=q.y;$('s'+q.id).value=q.q<0?'-1':'1';$('unit'+q.id).value=units[q.id];$('q'+q.id).value=Number((Math.abs(q.q)/(units[q.id]==='pC'?1e-12:1e-9)).toPrecision(12));
 }
 $('sourceCount').textContent=`${state.sources.length} / 4`;$('addSource').disabled=state.sources.length===4;$('px').value=state.point.x;$('py').value=state.point.y;
 for(const key of Object.keys(state.view))$(key).value=state.view[key];for(const key of DISPLAY)$(key).checked=state.display[key];$('autoScale').checked=state.autoScale;$('scale').value=state.scale;$('scale').disabled=state.autoScale;$('method').value=state.method;$('undo').disabled=!history.length;
}
function read(){const s=clone(state);s.sources=s.sources.map(q=>{const magnitude=num($('q'+q.id),`Q${q.id}`);if(magnitude<0)throw Error('Bitte einen nicht negativen Ladungsbetrag eingeben; das Vorzeichen separat wählen.');return{id:q.id,x:num($('x'+q.id),'x'),y:num($('y'+q.id),'y'),q:Number($('s'+q.id).value)*magnitude*($('unit'+q.id).value==='pC'?1e-12:1e-9)};});s.point={x:num($('px'),'P.x'),y:num($('py'),'P.y')};for(const key of Object.keys(s.view))s.view[key]=num($(key),'Ansicht');for(const key of DISPLAY)s.display[key]=$(key).checked;s.autoScale=$('autoScale').checked;if(!s.autoScale)s.scale=num($('scale'),'Pfeilmaßstab');s.method=$('method').value;return validate(s);}
function commit(next,{record=true,synchronize=true}={}){validate(next);if(record&&JSON.stringify(next)!==JSON.stringify(state)){history.push(clone(state));if(history.length>100)history.shift();}state=clone(next);inputInvalid=false;$('notice').textContent='';$('error').textContent='';$('example').value='custom';if(synchronize)sync();render();$('undo').disabled=!history.length;}
function updateFromInputs(){try{commit(read(),{synchronize:false});$('scale').disabled=state.autoScale;}catch(e){inputInvalid=true;$('error').textContent=e.message;$('result').textContent='Eingaben korrigieren; das Diagramm zeigt den letzten gültigen Aufbau.';$('pngExport').disabled=true;$('save').disabled=true;}}
function node(tag,attrs={},content,parent=svg){const n=document.createElementNS(NS,tag);for(const [key,v]of Object.entries(attrs))n.setAttribute(key,v);if(content!==undefined)n.textContent=content;parent.append(n);return n;}
function vectorGeometry(fields,res,scale){const P=state.point,end=(start,f)=>({x:start.x+f.x/scale,y:start.y+f.y/scale}),singles=fields.map(f=>({start:P,end:end(P,f),id:f.id})),helpers=[];let running={...P};if(state.method==='parallelogram'&&fields.length===2){for(let i=0;i<2;i++)helpers.push({start:singles[1-i].end,end:end(singles[1-i].end,fields[i]),id:fields[i].id});}else for(const f of fields){const finish=end(running,f);helpers.push({start:running,end:finish,id:f.id});running=finish;}return{singles,helpers,sum:{start:P,end:end(P,res)}};}
function chooseScale(fields,res){if(!state.autoScale)return state.scale;const g=vectorGeometry(fields,res,1),v=state.view,P=state.point,span=Math.min(v.xmax-v.xmin,v.ymax-v.ymin),available={left:Math.max(span*.1,P.x-v.xmin-.6),right:Math.max(span*.1,v.xmax-P.x-.6),up:Math.max(span*.1,v.ymax-P.y-.6),down:Math.max(span*.1,P.y-v.ymin-.6)};let scale=0;for(const p of [...g.singles.map(a=>a.end),...g.helpers.flatMap(a=>[a.start,a.end]),g.sum.end]){const x=p.x-P.x,y=p.y-P.y;scale=Math.max(scale,Math.abs(x)/(x<0?available.left:available.right),Math.abs(y)/(y<0?available.down:available.up));}if(scale<1e-12)return 1;const power=10**Math.floor(Math.log10(scale));return Math.max(1e-12,Math.min(1e15,Math.ceil(scale/power)*power));}
function render(){
 try{result=solve(state);$('error').textContent='';}catch(e){result=null;$('error').textContent=e.message;}
 const v=state.view,k=Math.min(680/(v.xmax-v.xmin),510/(v.ymax-v.ymin)),left=60+(680-(v.xmax-v.xmin)*k)/2,top=55+(510-(v.ymax-v.ymin)*k)/2,X=x=>left+(x-v.xmin)*k,Y=y=>top+(v.ymax-y)*k;
 transform={k,left,top,X,Y,x0:X(0),y0:Y(0)};const focused=document.activeElement?.dataset.point;svg.replaceChildren();node('rect',{width:800,height:650,fill:'white'});const defs=node('defs');
 const marker=(id,color)=>{const m=node('marker',{id,viewBox:'0 0 10 10',refX:9,refY:5,markerWidth:7,markerHeight:7,orient:'auto-start-reverse'},undefined,defs);node('path',{d:'M0 0 L10 5 L0 10z',fill:color},undefined,m);};COLORS.forEach((c,i)=>marker('e'+(i+1),c));marker('res','#126e67');marker('axis','#566661');const clip=node('clipPath',{id:'plotClip'},undefined,defs);node('rect',{x:left,y:top,width:(v.xmax-v.xmin)*k,height:(v.ymax-v.ymin)*k},undefined,clip);const plot=node('g',{'clip-path':'url(#plotClip)'});
 const text=(x,y,t,attrs={},parent=svg)=>node('text',{x,y,'font-family':'Arial, sans-serif','font-size':14,fill:'#233b38',...attrs},t,parent),line=(p,q,attrs={},parent=plot)=>node('line',{x1:X(p.x),y1:Y(p.y),x2:X(q.x),y2:Y(q.y),stroke:'#d8e0da','stroke-width':1,...attrs},undefined,parent);
 const step=Math.max(.1,10**Math.floor(Math.log10(Math.max(v.xmax-v.xmin,v.ymax-v.ymin)/12))),axisY=Math.max(v.ymin,Math.min(v.ymax,0)),axisX=Math.max(v.xmin,Math.min(v.xmax,0));
 for(let x=Math.ceil(v.xmin/step)*step;x<=v.xmax+step*1e-8;x+=step){if(state.display.grid)line({x,y:v.ymin},{x,y:v.ymax});text(X(x),Y(axisY)+18,fmt(Math.abs(x)<step*1e-8?0:x),{'text-anchor':'middle','font-size':12});}
 for(let y=Math.ceil(v.ymin/step)*step;y<=v.ymax+step*1e-8;y+=step){if(state.display.grid)line({x:v.xmin,y},{x:v.xmax,y});if(Math.abs(y)>step*1e-8)text(X(axisX)-8,Y(y)+4,fmt(y),{'text-anchor':'end','font-size':12});}
 if(v.ymin<=0&&v.ymax>=0)line({x:v.xmin,y:0},{x:v.xmax,y:0},{stroke:'#566661','marker-end':'url(#axis)'});if(v.xmin<=0&&v.xmax>=0)line({x:0,y:v.ymin},{x:0,y:v.ymax},{stroke:'#566661','marker-end':'url(#axis)'});text(X(v.xmax)-4,Y(axisY)-12,'x / cm',{'text-anchor':'end'});text(X(axisX)+12,Y(v.ymax)+13,'y / cm');
 if(state.display.guides)for(const q of state.sources)line(q,state.point,{'stroke-dasharray':'4 5'});effectiveScale=result?chooseScale(result.fields,result.res):state.scale;if(state.autoScale)$('scale').value=Number(effectiveScale.toPrecision(8));
 let geometry;if(result){geometry=vectorGeometry(result.fields,result.res,effectiveScale);
  const label=(x,y,id,color)=>{text(x,y,'E',{'font-family':'Georgia, serif','font-style':'italic','font-size':19,'paint-order':'stroke',stroke:'white','stroke-width':5,fill:color},plot);text(x+14,y+4,id,{'font-size':12,'paint-order':'stroke',stroke:'white','stroke-width':4,fill:color},plot);node('path',{d:`M${x-1} ${y-20} H${x+14} M${x+9} ${y-23} L${x+14} ${y-20} L${x+9} ${y-17}`,fill:'none',stroke:color,'stroke-width':1.3},undefined,plot);};
  const arrow=(a,id,dashed=false)=>{if(Math.hypot(a.end.x-a.start.x,a.end.y-a.start.y)<1e-9)return;const color=id==='res'?'#126e67':COLORS[Number(id)-1];line(a.start,a.end,{stroke:color,'stroke-width':dashed?1.7:3,'stroke-dasharray':dashed?'7 5':'','marker-end':`url(#${id==='res'?'res':'e'+id})`,'data-vector':id,'data-helper':String(dashed)});if(!dashed){const dx=X(a.end.x)-X(a.start.x),dy=Y(a.end.y)-Y(a.start.y),length=Math.hypot(dx,dy);let nx=-dy/length,ny=dx/length;if(nx*dx<0){nx=-nx;ny=-ny;}label((X(a.start.x)+X(a.end.x))/2+nx*26-8,(Y(a.start.y)+Y(a.end.y))/2+ny*26+8,id,color);}};
  if(state.display.construction)for(const a of geometry.helpers)arrow(a,String(a.id),true);if(state.display.vectors)for(const a of geometry.singles)arrow(a,String(a.id));if(state.display.sum&&!result.zero)arrow(geometry.sum,'res');
 }
 const point=(id,p,q)=>{const g=node('g',{'data-point':id,tabindex:0,role:'button','aria-label':`${id==='P'?'Feldort P':id}, ${fmt(p.x)} und ${fmt(p.y)} cm. Pfeiltasten zum Verschieben.`},undefined,plot);node('circle',{cx:X(p.x),cy:Y(p.y),r:22,fill:'transparent',stroke:'transparent',class:'focus-ring'},undefined,g);node('circle',{cx:X(p.x),cy:Y(p.y),r:q===null?6:13,fill:q===null?'#126e67':q===0?'#899590':q>0?'#be5147':'#427fa8',stroke:'#233b38','stroke-width':1.5,class:'point-symbol'},undefined,g);if(q!==null)text(X(p.x),Y(p.y)+6,q===0?'0':q>0?'+':'−',{'text-anchor':'middle',fill:'white','font-size':22},g);text(X(p.x)+16,Y(p.y)+22,`${id} (${fmt(p.x)}|${fmt(p.y)})`,{'paint-order':'stroke',stroke:'white','stroke-width':4,'stroke-linejoin':'round'},plot);};
 for(const q of state.sources)point('Q'+q.id,q,q.q);point('P',state.point,null);text(40,25,'Feldvektoren am Feldort P · P ist keine Ladung',{'font-size':17,'font-weight':'bold'});text(40,44,state.sources.map(q=>`Q${q.id} = ${fmt(q.q/1e-12)} pC`).join(' · ')||'Keine Quellladungen',{'font-size':12});text(40,612,`Ortsraster: ${fmt(step)} cm · Pfeilmaßstab: ${fmt(effectiveScale)} V/m je 1 cm im Ortsraster`,{'font-size':13});text(40,636,'Feste Quellladungen · verschobene Pfeile sind geometrische Kopien der Beiträge in P.',{'font-size':12});
 const outside=p=>p.x<v.xmin||p.x>v.xmax||p.y<v.ymin||p.y>v.ymax;$('viewHint').textContent=[...state.sources,state.point].some(outside)?'Ein Punkt liegt außerhalb der Ansicht. Unter „Ansicht einstellen“ kannst du die Grenzen anpassen.':geometry&&([...geometry.singles,...geometry.helpers,geometry.sum].some(a=>outside(a.end)))?'Ein Feldpfeil reicht über die Ansicht hinaus. Auto-Maßstab aktivieren oder den Pfeilmaßstab vergrößern.':'';
 $('methodHint').textContent=state.method==='parallelogram'&&state.sources.length!==2?'Das Parallelogramm gilt für zwei Beiträge. Für diesen Aufbau wird eine Pfeilkette gezeichnet.':'';
 $('result').textContent=!result?'Feld am Quellort nicht definiert. P verschieben, um weiterzurechnen.':!state.display.sum?'Resultierende ausgeblendet.':`Eres = (${fmt(result.res.x)} | ${fmt(result.res.y)}) V/m · Betrag: ${result.zero?'0':fmt(result.magnitude)} V/m · ${result.zero?'keine Richtung (Nullfeld)':`Richtung: ${fmt(result.angle)}° gegen +x`}`;
 $('contributions').replaceChildren();if(result&&state.display.vectors&&result.fields.length){const table=document.createElement('table');table.innerHTML='<thead><tr><th>Beitrag</th><th>Abstand / cm</th><th>Ex / V/m</th><th>Ey / V/m</th><th>|E| / V/m</th></tr></thead>';const tbody=document.createElement('tbody');for(const f of result.fields){const row=document.createElement('tr');row.innerHTML=`<td><span class="swatch" style="background:${COLORS[f.id-1]}"></span>E${f.id}</td><td>${fmt(f.distance*100)}</td><td>${fmt(f.x)}</td><td>${fmt(f.y)}</td><td>${fmt(f.mag)}</td>`;tbody.append(row);}table.append(tbody);$('contributions').append(table);}
 $('pngExport').disabled=!result;$('save').disabled=false;if(focused)svg.querySelector(`[data-point="${focused}"]`)?.focus({preventScroll:true});
}
function setTool(next){tool=next;document.querySelectorAll('[data-tool]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tool===tool)));$('toolHint').textContent=tool==='move'?'Ziehe P oder eine Quellladung. Mit den Pfeiltasten bewegst du einen fokussierten Punkt.':tool==='point'?'Tippe auf die Zeichenfläche, um P dort zu setzen.':'Tippe auf die Zeichenfläche, um eine Quelle mit 10 pC zu setzen (maximal vier).';}
function addSource(x=0,y=0,sign=1){if(inputInvalid){$('notice').textContent='Bitte zuerst die Eingaben korrigieren.';return;}if(state.sources.length===4){$('notice').textContent='Vier Quellladungen sind bereits gesetzt. Entferne eine Quelle, um eine neue zu setzen.';return;}const next=clone(state),id=[1,2,3,4].find(n=>!next.sources.some(q=>q.id===n));next.sources.push({id,x,y,q:sign*DEFAULT_CHARGE});next.sources.sort((a,b)=>a.id-b.id);units[id]='pC';commit(next);}
function coordinates(e){const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(svg.getScreenCTM().inverse());return{x:Math.round((p.x-transform.x0)/transform.k*10)/10,y:Math.round((transform.y0-p.y)/transform.k*10)/10};}
svg.addEventListener('pointerdown',e=>{if(inputInvalid){$('notice').textContent='Bitte zuerst die Eingaben korrigieren.';return;}const p=coordinates(e),id=e.target.closest('[data-point]')?.dataset.point;if(id&&tool==='move'){drag={id,before:clone(state)};svg.setPointerCapture(e.pointerId);e.target.closest('[data-point]').focus({preventScroll:true});}else if(tool==='point'){const next=clone(state);next.point=p;commit(next);}else if(tool==='positive'||tool==='negative')addSource(p.x,p.y,tool==='positive'?1:-1);});
svg.addEventListener('pointermove',e=>{if(!drag)return;const p=coordinates(e),next=clone(state);if(drag.id==='P')next.point=p;else Object.assign(next.sources.find(q=>'Q'+q.id===drag.id),p);try{commit(next,{record:false,synchronize:false});if(drag.id==='P'){$('px').value=p.x;$('py').value=p.y;}else{const id=drag.id.slice(1);$('x'+id).value=p.x;$('y'+id).value=p.y;}}catch(error){$('error').textContent=error.message;}});
function finishDrag(){if(drag){if(JSON.stringify(state)!==JSON.stringify(drag.before)){history.push(drag.before);if(history.length>100)history.shift();}drag=null;$('undo').disabled=!history.length;}}svg.addEventListener('pointerup',finishDrag);svg.addEventListener('pointercancel',finishDrag);
svg.addEventListener('keydown',e=>{const id=e.target.dataset.point;if(!id||inputInvalid||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const next=clone(state),p=id==='P'?next.point:next.sources.find(q=>'Q'+q.id===id),step=e.shiftKey?1:.1;p.x=Number((p.x+(e.key==='ArrowLeft'?-step:e.key==='ArrowRight'?step:0)).toFixed(10));p.y=Number((p.y+(e.key==='ArrowDown'?-step:e.key==='ArrowUp'?step:0)).toFixed(10));try{commit(next);}catch(error){$('error').textContent=error.message;}});
$('sources').addEventListener('click',e=>{const id=Number(e.target.closest('[data-remove]')?.dataset.remove);if(id){const next=clone(state);next.sources=next.sources.filter(q=>q.id!==id);commit(next);}});
$('sources').addEventListener('input',e=>{if(e.target.dataset.key!=='unit')updateFromInputs();});
$('sources').addEventListener('change',e=>{if(e.target.dataset.key==='unit'){const id=Number(e.target.closest('[data-source]').dataset.source);if(inputInvalid){e.target.value=units[id];return;}units[id]=e.target.value;$('q'+id).value=Number((Math.abs(state.sources.find(q=>q.id===id).q)/(units[id]==='pC'?1e-12:1e-9)).toPrecision(12));}else updateFromInputs();});
for(const key of ['px','py','scale','xmin','xmax','ymin','ymax'])$(key).addEventListener('input',updateFromInputs);for(const key of [...DISPLAY,'method','autoScale'])$(key).addEventListener('change',updateFromInputs);
document.querySelectorAll('[data-tool]').forEach(b=>b.addEventListener('click',()=>setTool(b.dataset.tool)));$('addSource').onclick=()=>addSource();$('undo').onclick=()=>{const previous=history.pop();if(previous)commit(previous,{record:false});};
$('fitView').onclick=()=>{if(inputInvalid)return;const next=clone(state),points=[...next.sources,next.point,{x:0,y:0}],xs=points.map(p=>p.x),ys=points.map(p=>p.y);next.view={xmin:Math.min(...xs)-2,xmax:Math.max(...xs)+2,ymin:Math.min(...ys)-2,ymax:Math.max(...ys)+2};commit(next);};
$('example').onchange=()=>{const preset=$('example').value;if(preset==='custom')return;let next=defaultState();if(preset==='empty')next.sources=[];if(preset==='single')next.sources=[{id:1,x:0,y:0,q:DEFAULT_CHARGE}];if(preset==='four')next.sources=[{id:1,x:0,y:0,q:DEFAULT_CHARGE},{id:2,x:6,y:0,q:-DEFAULT_CHARGE},{id:3,x:0,y:8,q:-DEFAULT_CHARGE},{id:4,x:6,y:8,q:DEFAULT_CHARGE}];if(preset==='bookDipole'||preset==='bookPositive'){const old=preset==='bookDipole'?{x1:0,y1:0,s1:-1,e1:2,x2:6,y2:0,s2:1,e2:2,px:3,py:4,scale:1}:{x1:0,y1:0,s1:1,e1:4,x2:8,y2:2,s2:1,e2:8,px:5,py:6,scale:1};next=importState({version:1,settings:old});next.autoScale=true;}units={};setTool('move');commit(next);$('example').value=preset;};
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const safe=fn=>async()=>{try{await fn();}catch(e){$('notice').textContent=e.message;}};
$('pngExport').onclick=safe(async()=>{if(inputInvalid||!result)throw Error('Bitte vor dem Export die Eingaben korrigieren.');const copy=svg.cloneNode(true);copy.setAttribute('width','800');copy.setAttribute('height','650');const url=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(copy)],{type:'image/svg+xml'}));try{const img=new Image();img.src=url;await img.decode();const c=document.createElement('canvas');c.width=1600;c.height=1300;c.getContext('2d').drawImage(img,0,0,c.width,c.height);const blob=await new Promise(resolve=>c.toBlob(resolve,'image/png'));if(!blob)throw Error('PNG konnte nicht erzeugt werden.');download(blob,'feldvektoren.png');}finally{URL.revokeObjectURL(url);}});
$('save').onclick=safe(()=>{if(inputInvalid)throw Error('Bitte vor dem Speichern die Eingaben korrigieren.');download(new Blob([JSON.stringify({version:2,settings:state},null,2)],{type:'application/json'}),'feldvektoren.json');});$('load').onclick=()=>$('file').click();$('file').onchange=safe(async()=>{const file=$('file').files[0];if(!file)return;try{if(file.size>100000)throw Error('Die Aufbau-Datei ist zu groß.');const obj=JSON.parse(await file.text()),next=importState(obj);units={};commit(next);if(obj.version===1){$('fitView').click();$('notice').textContent='Alte Aufgabe geladen: Ladungsbeträge wurden so berechnet, dass die früheren Feldwerte im ursprünglichen P erhalten bleiben. Beim Verschieben gelten jetzt feste Ladungen.';}}finally{$('file').value='';}});
window.__fieldVectorWorkshop={solve,importState,getState:()=>clone(state),getResult:()=>result?clone(result):null,getScale:()=>effectiveScale};sync();render();
